import Head from 'next/head'
import Header from '../components/Header'

export default function Home() {
  return (
    <div className="w-full">
      <Head>
        <title>SHTEM Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="container pt-12">
        <h1 className="text-7xl font-bold text-center">
          Hello
        </h1>
      </main>
    </div>
  )
}
