import Link from "next/link"
export default function terms () {
    return (
        <>


            <main className="container pt-12 pb-24">
                <h1 className="text-5xl font-bold text-center mb-12">
                    Buy our things
                </h1>
                <div className=" flex justify-center gap-4 flex-wrap">
                    <p>

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus fermentum elit non magna mollis, in porttitor eros iaculis. Integer ut nisl congue, laoreet tortor nec, lacinia quam. Quisque et urna elementum, imperdiet est eu, ornare nisi. Ut pretium, sem eu pretium imperdiet, arcu nibh blandit leo, non mollis felis nisi eget justo. Morbi nisi nisl, ultricies id turpis eget, ullamcorper placerat arcu. Cras sollicitudin pharetra ipsum. Vivamus at massa in justo placerat consequat. Suspendisse non sodales nunc. Phasellus scelerisque rutrum venenatis. Maecenas posuere tellus lorem, posuere tempus turpis pellentesque ac. Fusce sit amet maximus turpis. Donec pellentesque ante sed semper condimentum. Cras eu nunc congue, dictum mi ac, tristique ex. Phasellus luctus maximus ultrices. Morbi ornare vehicula eros, sit amet mattis nunc malesuada et. Nunc semper gravida lorem nec iaculis.

Integer hendrerit, leo eleifend varius accumsan, magna sapien commodo libero, efficitur vestibulum tellus risus vel sem. Nam pretium id sapien non maximus. Quisque sed lorem leo. Quisque pharetra rutrum commodo. Morbi sagittis sapien a ex pharetra, nec pretium enim vulputate. Phasellus id tellus vitae justo consequat scelerisque non ut enim. Sed condimentum arcu ac libero ultricies tristique. Donec vitae condimentum enim. Fusce faucibus eros ut nibh placerat vestibulum. Phasellus non urna eu quam sagittis molestie nec in elit. Cras nulla neque, interdum sit amet venenatis a, pellentesque id felis. Proin venenatis sollicitudin sem, et venenatis felis tempor in. Donec tincidunt aliquam quam vel pellentesque. Donec ex quam, congue quis nulla eget, convallis eleifend est.

Sed vitae efficitur enim. Cras ac mi non metus placerat porttitor. Mauris vel varius nunc. Vestibulum lacinia posuere lorem eu ultricies. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque nec dui vel orci elementum convallis tincidunt vitae dui. Etiam a semper eros. Donec aliquam vel tellus dictum mattis. Morbi sed varius sem, quis elementum felis. Quisque venenatis iaculis quam dictum interdum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Phasellus tempus molestie nibh, non congue est blandit sit amet. Mauris et leo at quam fermentum vehicula. Donec tristique libero ac molestie eleifend. Mauris placerat fermentum nibh, ac scelerisque risus accumsan sed. Nullam id pretium eros. Curabitur tincidunt, felis eu commodo faucibus, risus leo sollicitudin mauris, eu ornare nibh nulla dignissim quam. Pellentesque non dictum purus. Fusce erat diam, hendrerit et tincidunt quis, tristique ac nisl. Etiam sit amet metus et ipsum sollicitudin ultricies dignissim quis sem. Praesent pellentesque ligula lectus, vel ultrices mi volutpat egestas. Nam molestie dolor ac efficitur ornare. Nulla varius cursus libero, nec accumsan metus ullamcorper ut. Aenean convallis eros lacus, eu interdum nibh convallis at. Quisque quis facilisis odio.

Duis condimentum pharetra justo, ut varius eros mattis et. Duis vulputate nulla lectus, vel sollicitudin metus sodales id. Maecenas elementum pretium urna ac ultrices. Nulla placerat, mauris sed vestibulum tempor, nulla quam dapibus enim, id dictum leo lacus sit amet dui. Aliquam erat volutpat. Nunc rutrum volutpat dolor et sagittis. Duis tempor, eros a imperdiet porttitor, elit dui commodo ipsum, quis finibus tortor est ut massa. Aliquam congue arcu nulla, vitae hendrerit lectus aliquet et. Nam suscipit vitae urna in hendrerit. Proin elementum erat leo, vitae bibendum velit tincidunt in. Etiam scelerisque suscipit justo, sed cursus enim. Vestibulum maximus nunc velit, ut auctor odio commodo eu.

In quis vestibulum lectus. Integer ut lacus elit. Nunc viverra nulla et laoreet feugiat. Donec tortor felis, rhoncus porttitor tristique nec, hendrerit at lectus. Nunc ullamcorper, dolor sit amet condimentum iaculis, enim magna rutrum metus, in euismod dolor justo nec ex. Nullam ac sapien finibus, cursus enim eu, viverra eros. Aliquam tempor sem sit amet ullamcorper congue. Suspendisse ultrices, est eu viverra lobortis, augue sapien semper felis, in tincidunt nisl libero sed libero. Phasellus euismod, risus sit amet tristique tincidunt, nulla enim vehicula ex, et ullamcorper lectus arcu maximus erat. Quisque venenatis eleifend sagittis.

Nunc placerat risus eget tellus scelerisque, eget maximus est laoreet. Proin fringilla auctor metus, eget rutrum nisl. Vivamus rhoncus nunc quis ligula ultricies dictum. Mauris egestas fermentum lorem, ut suscipit leo pellentesque id. Curabitur sed posuere nisi, ac tempus quam. Fusce venenatis lacinia lacus, et sollicitudin dui hendrerit non. Suspendisse eu hendrerit lectus. Suspendisse at euismod leo. Aliquam rhoncus purus quis quam rhoncus dapibus. Nulla ac sollicitudin libero. Duis congue fermentum mi tincidunt efficitur. Donec a maximus mi. Maecenas condimentum metus nec nunc pharetra, et tempor purus venenatis. Integer varius elit at nunc auctor, a dapibus sapien volutpat. Quisque rutrum odio id iaculis luctus.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed odio metus, interdum vitae quam suscipit, gravida dictum tellus. Mauris mollis turpis eu posuere ultrices. Nunc hendrerit ipsum velit. Proin nec dui dui. Nullam tortor purus, aliquam sit amet turpis non, mattis volutpat libero. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ut leo lacus. Quisque ultricies neque nibh, eu hendrerit nibh suscipit a. Aliquam leo sem, dignissim id est nec, mattis molestie arcu. Curabitur tincidunt nec ante at semper. Nam at metus consequat, rhoncus lacus nec, dignissim sem. Sed quis sapien maximus nibh rhoncus convallis. In vitae lobortis metus.

Fusce tincidunt cursus viverra. Pellentesque tortor lacus, tristique in feugiat vel, feugiat in est. Etiam enim quam, imperdiet ut purus in, malesuada blandit diam. Phasellus mauris magna, venenatis ut lectus sed, interdum aliquet nunc. Ut lacinia velit eget mauris pretium, venenatis varius lectus porttitor. Quisque auctor enim purus, sed luctus arcu lacinia aliquam. Mauris at suscipit lectus, in vestibulum leo. Quisque nec augue in lectus dignissim mattis non et ante. Nullam tempus ipsum non augue rutrum commodo.

Nam sit amet condimentum mi. Donec finibus, odio in bibendum porta, eros nisl cursus diam, sed elementum neque tortor et sem. Vivamus eu eros metus. Curabitur suscipit ac quam ut commodo. Integer eget tellus congue mi malesuada laoreet nec vel lorem. Nam quis tortor vel ex aliquet tincidunt ut non diam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec pharetra est risus.

Praesent lobortis tortor ac risus volutpat, non ultricies turpis tempus. In sit amet velit nec turpis porttitor ultrices in id nunc. Morbi at venenatis nisl. Morbi porta dictum lacus sed luctus. Fusce ornare, ante ac tincidunt auctor, nibh nisl tincidunt sapien, at gravida magna neque vel elit. Nunc quis purus vitae dolor tempus efficitur eget nec lorem. Fusce tristique tellus a eros dapibus, nec pretium nulla hendrerit. Aliquam vel dolor ac augue congue aliquam. Nulla facilisi. Nulla varius lectus libero, sed congue ex condimentum sit amet. Donec cursus congue ex ac rutrum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris nec mi justo.

Praesent volutpat sagittis nisl eget commodo. Suspendisse cursus commodo arcu, consectetur luctus tortor consequat vitae. Curabitur suscipit mi sit amet orci convallis, eu feugiat velit pulvinar. Curabitur porta urna nec mi pulvinar ultrices. Aenean at augue auctor nunc ultrices venenatis. Donec rutrum quis enim vitae sollicitudin. Aliquam cursus, mauris id suscipit condimentum, turpis odio vestibulum urna, sed rutrum tellus ex eu enim. Phasellus viverra vel nisl a auctor. Suspendisse aliquet condimentum iaculis.

Nullam feugiat massa sit amet nisl iaculis porttitor. Curabitur id suscipit orci. Morbi dui erat, sodales ut sem sed, ultricies vestibulum massa. Proin malesuada neque nec eros sollicitudin, ac imperdiet neque malesuada. Nulla porttitor massa quis erat maximus, vel tincidunt quam rhoncus. Nam semper velit non cursus congue. Nullam aliquam tincidunt quam in ultrices. Nam euismod arcu urna, ac mattis diam aliquet a. Nulla interdum rutrum augue quis scelerisque. Etiam congue lectus sit amet malesuada sollicitudin. Pellentesque metus nibh, ultricies a ex sed, pretium fermentum erat. Pellentesque ac convallis lacus. In nunc sem, congue non interdum tristique, congue nec felis. Curabitur egestas orci in molestie porta.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eget magna quis lacus imperdiet cursus consectetur id libero. Etiam feugiat justo sit amet tellus dapibus luctus. Proin pulvinar dui a lobortis sollicitudin. Cras mattis tempus tortor, eget ullamcorper ipsum facilisis vel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nec nunc non quam fermentum vehicula et non risus. Integer euismod, lorem id ornare porta, mauris lorem mollis orci, vitae egestas enim metus eget tellus. Phasellus eros augue, malesuada eget gravida id, faucibus nec arcu. Phasellus auctor nunc leo, non laoreet libero tincidunt vitae. Vivamus commodo pellentesque magna et venenatis.

Proin nisi elit, venenatis a erat eget, tristique molestie leo. In blandit, lorem quis volutpat rhoncus, nibh metus posuere lorem, a euismod metus urna at nisi. Suspendisse velit lacus, vehicula vitae sodales at, vulputate sed tellus. Curabitur fermentum in leo eu facilisis. Proin vestibulum, ex in dictum finibus, libero arcu luctus enim, nec interdum nulla dolor et lorem. Donec vitae lacus ac est posuere tristique. Aliquam urna nisi, pretium quis consequat vitae, ullamcorper et magna. Donec facilisis, est non luctus porttitor, sem ante fermentum massa, ac egestas arcu orci ac orci. Nullam id bibendum dolor.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus eget finibus dolor. Nunc elementum neque eget justo consectetur, nec volutpat dolor scelerisque. Integer bibendum velit sit amet nisi sollicitudin, vitae lobortis mi molestie. Fusce hendrerit fermentum leo, id hendrerit dolor efficitur ut. Suspendisse non ligula tempus, tincidunt tellus in, consequat purus. Quisque accumsan, nunc nec aliquet pharetra, mauris metus rutrum magna, ut rutrum purus ligula eget purus. Duis vel mi ut ligula consequat tempor. Duis non eleifend mi. Nunc vel felis orci. Nunc fermentum urna at est aliquet, eget luctus est faucibus. Suspendisse tincidunt luctus orci nec commodo. Donec quam erat, varius at tincidunt ac, vulputate non neque.

Aliquam a lectus eu diam placerat fringilla fringilla vitae leo. Sed mollis est et euismod pulvinar. Nunc suscipit sit amet est quis efficitur. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse vel fermentum purus. Maecenas sodales viverra tellus, eu suscipit arcu lacinia a. Aenean commodo pretium mauris sit amet egestas. Fusce molestie efficitur risus, sit amet fringilla leo vulputate aliquam. Donec vel sagittis augue.

In et diam vitae quam pellentesque elementum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque sed finibus quam. Quisque ligula felis, suscipit ac vehicula ut, fringilla in neque. Morbi luctus ante odio, molestie accumsan nunc fermentum nec. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Maecenas mattis venenatis massa, a blandit est gravida auctor. Praesent in rutrum risus, in pharetra libero. Nam nec orci et tellus hendrerit suscipit vitae rutrum ex. Nullam interdum tellus ac euismod efficitur. Sed eget massa consequat, malesuada nunc vel, volutpat odio. Nulla consequat in nisl vitae placerat. In maximus lorem ut massa cursus, quis sollicitudin nisl iaculis.

Sed rutrum dui in tellus suscipit, ut viverra erat mattis. Curabitur eget ante porttitor, ultrices tortor quis, viverra felis. Praesent non gravida eros. Ut sodales laoreet libero, quis facilisis ligula egestas eget. Cras aliquet pellentesque enim, a lobortis leo scelerisque suscipit. Curabitur dictum tellus eget massa malesuada mollis. Fusce facilisis, metus volutpat aliquet suscipit, mi eros interdum est, ullamcorper sagittis tortor massa a turpis. Sed eu convallis nisi, volutpat ornare enim. Praesent ex dui, tincidunt at odio quis, faucibus pellentesque felis. Vivamus massa tellus, mattis vitae lobortis et, dapibus viverra turpis. Nunc ultrices tellus id magna tempor porta.

Integer tristique purus in suscipit convallis. Aliquam in rutrum dolor, et auctor mauris. Nam congue lobortis rhoncus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed convallis iaculis risus. In sodales mattis velit, in ultrices ante facilisis ut. Fusce imperdiet tortor et arcu ornare, ut tincidunt erat finibus. Mauris non consectetur massa.

Integer eget vehicula velit. Pellentesque aliquet a velit sodales elementum. Fusce at iaculis turpis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Quisque aliquet mauris nulla, sit amet malesuada libero scelerisque vel. Integer sit amet venenatis orci. Pellentesque a mi at tortor aliquet varius quis quis purus. Donec ac consequat justo.

Cras consequat elementum leo, non efficitur lectus mollis id. Donec sed sem in ligula tincidunt pulvinar id sit amet quam. Etiam in maximus diam, non lacinia leo. Mauris ipsum quam, cursus in ipsum eget, tristique ornare diam. Nulla lacinia, dui nec malesuada consequat, arcu nisi tempus mi, vel blandit nisl dui ut ante. Aliquam erat volutpat. Morbi vel augue dapibus, pulvinar quam et, dictum dui. Fusce rhoncus sagittis dignissim. Nullam sem dui, facilisis blandit elit vel, pretium ultricies erat. Donec pellentesque luctus lacus vel euismod. Phasellus aliquam consequat massa vel ullamcorper. Nulla pretium tempor congue. Mauris velit nulla, gravida et lorem ac, faucibus dapibus leo. In nec odio nec quam ullamcorper dictum eget vitae est. Nulla id eros nec nibh luctus varius. Curabitur malesuada congue urna, vitae suscipit felis scelerisque et.

Morbi porttitor sapien massa, ac fringilla dolor euismod eget. Proin in leo non est vestibulum hendrerit. Donec id ante laoreet, consequat diam a, consectetur orci. Praesent sit amet aliquet ipsum. Etiam commodo quam arcu, id pharetra mi convallis at. Aenean nec lorem tincidunt, pulvinar ligula vitae, rhoncus nulla. Donec auctor neque mi, in ultrices lacus molestie quis. Praesent tempus hendrerit nisi a auctor.

Nulla rutrum diam sit amet sollicitudin varius. Vestibulum eros ligula, vestibulum vitae ullamcorper fringilla, hendrerit eu nisl. Integer iaculis, ante ut posuere interdum, risus urna lacinia urna, eu laoreet lectus est a velit. Nunc in risus porttitor, ultricies sem ut, cursus ipsum. Sed eleifend magna sit amet lacinia vehicula. Ut a dictum lectus. Duis pharetra a justo ut faucibus.

Sed quis pharetra odio. Cras ultrices dolor a diam tincidunt consequat. Morbi condimentum semper sodales. Quisque cursus lectus eu dolor condimentum tincidunt. Sed quam justo, rutrum sed tristique sed, malesuada vel lorem. Vestibulum vulputate eros arcu, at cursus orci accumsan sed. Praesent nisi dui, commodo lacinia consectetur vitae, accumsan vitae augue. Nulla malesuada finibus elementum. Nullam vitae imperdiet eros. Vivamus sit amet elit arcu. Sed blandit porta velit ut molestie. Nulla rutrum mi ut cursus vestibulum.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Quisque sed nisi in augue pellentesque viverra. Fusce vitae nisl at elit auctor faucibus. Nullam aliquet, odio sit amet viverra imperdiet, magna turpis consequat magna, ut blandit enim urna eu ex. Sed elementum pharetra urna sed rutrum. Curabitur eu ante sit amet risus ullamcorper cursus. Etiam non egestas ligula. Quisque vitae ante ac ligula pretium tempus ac eu sapien. Curabitur eget faucibus erat. Maecenas non erat sit amet tortor accumsan feugiat eget et diam. Phasellus et turpis lorem. Morbi convallis magna orci, in tempor odio placerat vel. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus dictum est eu tincidunt ullamcorper.

Nam est est, pretium condimentum pretium venenatis, efficitur non odio. Cras ac tellus sed leo faucibus aliquet sagittis sit amet velit. Aliquam sapien ex, maximus quis lobortis quis, fringilla sodales risus. Ut vehicula condimentum tortor. Fusce commodo sodales elit, id sollicitudin justo finibus ut. In non purus ornare, varius nisi ac, tempor dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nunc blandit felis quis dui feugiat, non vulputate dui faucibus. Morbi rhoncus quis augue eget vehicula. Curabitur metus nisl, tincidunt in tristique at, rhoncus id ligula. Quisque venenatis vel lorem non hendrerit.

Vivamus vehicula augue sit amet augue commodo accumsan. Nulla ultricies massa velit, ac ultrices mauris molestie non. Aliquam pulvinar justo arcu, sit amet vulputate justo congue ullamcorper. Morbi feugiat facilisis enim in cursus. Maecenas scelerisque, nulla ornare euismod efficitur, nibh purus dignissim ante, eget accumsan ligula tellus sed quam. Nulla gravida turpis velit, quis tristique ligula maximus eget. Vivamus efficitur nisi molestie nibh ultricies venenatis. Aliquam erat libero, interdum vel pharetra in, faucibus id risus. Cras tempus sem sed ante fermentum gravida. Etiam eget eleifend erat. Phasellus dapibus massa in massa luctus gravida. Donec semper lacinia ligula sollicitudin luctus.

Suspendisse sodales pellentesque elit quis rhoncus. Nunc imperdiet rutrum vestibulum. Donec efficitur dolor eget odio ultrices, in semper massa consectetur. Nunc eget ante sit amet velit pellentesque vestibulum interdum non enim. Sed accumsan purus non magna eleifend laoreet. Nulla imperdiet rutrum mauris, vitae gravida ex vehicula et. Nullam tempor sollicitudin quam ut fringilla. In tincidunt leo eu semper pulvinar.

Aenean vel iaculis quam. Sed cursus mauris vel orci gravida, eget sodales sem dictum. Suspendisse in lectus id quam efficitur lacinia ac et velit. Nulla facilisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam consectetur mollis tristique. Etiam eu nisi vel nisl efficitur gravida. Suspendisse metus ipsum, eleifend sed vehicula a, vestibulum nec purus. Nulla velit lectus, porttitor ac justo vel, pellentesque varius nulla. Praesent luctus tortor eget nunc rutrum viverra. Quisque tempor vulputate mi, at ultricies quam tristique vitae. Suspendisse nec malesuada nisi. Fusce tempor facilisis nunc eu mattis. Cras facilisis tellus eros, sed consequat diam congue eu. Morbi eget malesuada nunc, eget luctus tellus.
                  </p>
                </div>
                <br></br>
                <div className="text-5xl font-bold text-center mb-12">
                <Link href="/home">
                    <a><button>I agree to Terms and Conditions</button></a>
                </Link>
                </div>
            </main>
        </>
    )
                    }